version: '3'
services:
   api:
      image: cristhiankr/atucasa-service:dev
      container_name: service
      command: python manage.py runserver 0.0.0.0:8933
      volumes:
        - .:/atucasa
      ports:
        - "8933:8933"
   web:
      image: cristhiankr/atucasa-web:dev
      container_name: web
      ports: 
         - "80:80"

       
