# Generated by Django 3.0.6 on 2020-06-01 04:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('contact_phone', models.CharField(default='123456789', max_length=32, verbose_name='Teléfono de contacto')),
                ('type_identification', models.CharField(default='CC', max_length=20, verbose_name='Tipo de identificación')),
                ('identification', models.CharField(default='123456789', max_length=12, verbose_name='Número de identificación')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre sede')),
                ('direction', models.CharField(blank=True, max_length=256, null=True, verbose_name='Dirección')),
                ('coor_x', models.CharField(blank=True, max_length=16, null=True, verbose_name='Coordenada x')),
                ('coor_y', models.CharField(blank=True, max_length=16, null=True, verbose_name='Coordenada y')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Número teléfono')),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='Correo electrónico')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Fecha última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('delete', models.BooleanField(default=False, verbose_name='Eliminado')),
            ],
            options={
                'verbose_name': 'Branch',
                'db_table': 'atc_branch',
            },
        ),
        migrations.CreateModel(
            name='Category_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre Categoría')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Descripción')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Fecha última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('delete', models.BooleanField(default=False, verbose_name='Eliminado')),
            ],
            options={
                'verbose_name': 'Category_product',
                'db_table': 'atc_category_product',
            },
        ),
        migrations.CreateModel(
            name='Category_Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre Categoría')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='Descripción')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Fecha última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('delete', models.BooleanField(default=False, verbose_name='Eliminado')),
            ],
            options={
                'verbose_name': 'Category_store',
                'db_table': 'atc_category_store',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Ciudad o Municipio')),
                ('departament', models.CharField(max_length=64, verbose_name='Departamento')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Fecha última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('delete', models.BooleanField(default=False, verbose_name='Eliminado')),
            ],
            options={
                'verbose_name': 'City',
                'db_table': 'atc_city',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre Tienda')),
                ('url_logo', models.URLField(max_length=248, verbose_name='Logotipo')),
                ('description', models.CharField(max_length=512, verbose_name='Descripción de la empresa')),
                ('email', models.CharField(blank=True, max_length=512, null=True, verbose_name='Correo electrónico')),
                ('contact_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombre de contacto')),
                ('phone', models.CharField(max_length=32, verbose_name='Número teléfono')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Fecha última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('delete', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('category_store', models.ManyToManyField(to='atucasa.Category_Store', verbose_name='Tiendas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Store',
                'db_table': 'atc_store',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre producto')),
                ('description', models.CharField(max_length=512, verbose_name='Descripción')),
                ('presentation', models.CharField(max_length=64, verbose_name='Presentación')),
                ('price', models.BigIntegerField(verbose_name='Precio')),
                ('brand', models.CharField(blank=True, max_length=32, null=True, verbose_name='Marca')),
                ('units', models.IntegerField(verbose_name='Unidades disponibles')),
                ('discount_porcentual', models.DecimalField(decimal_places=3, max_digits=3, verbose_name='Porcentaje de descuento')),
                ('url_image', models.URLField(max_length=256, verbose_name='Imagen')),
                ('name_store', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombre tienda')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Fecha última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Estado')),
                ('delete', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atucasa.Branch', verbose_name='Sede')),
                ('category_product', models.ManyToManyField(to='atucasa.Category_Product', verbose_name='Categoria')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atucasa.Store', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Product',
                'db_table': 'atc_product',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atucasa.City', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='branch',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atucasa.Store', verbose_name='Tienda'),
        ),
    ]
