# Generated by Django 3.0.6 on 2020-06-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atucasa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_porcentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de descuento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='presentation',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Presentación'),
        ),
    ]
