# Generated by Django 3.0.6 on 2020-06-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atucasa', '0002_auto_20200611_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_image',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Imagen'),
        ),
    ]
