# Generated by Django 3.0.6 on 2020-06-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atucasa', '0003_auto_20200611_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='category_product',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='category_store',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='city',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='store',
            name='delete',
        ),
    ]
