# Generated by Django 3.0.6 on 2020-07-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atucasa', '0004_auto_20200620_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star',
            field=models.BooleanField(default=False, verbose_name='start'),
        ),
        migrations.AddField(
            model_name='store',
            name='star',
            field=models.BooleanField(default=False, verbose_name='start'),
        ),
    ]
