# Generated by Django 3.0.6 on 2020-07-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atucasa', '0005_auto_20200712_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_porcentual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Porcentaje de descuento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_identification',
            field=models.CharField(default='NIT', max_length=20, verbose_name='Tipo de identificación'),
        ),
    ]
