# Generated by Django 3.0.6 on 2020-07-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atucasa', '0006_auto_20200714_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_product',
            name='url_image',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='Imagen'),
        ),
    ]
    